//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moder.Language.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Moder.Language.Strings.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 人物编辑器.
        /// </summary>
        public static string Menu_CharacterEditor {
            get {
                return ResourceManager.GetString("Menu.CharacterEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        public static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App 语言.
        /// </summary>
        public static string SettingsPage_AppLanguage {
            get {
                return ResourceManager.GetString("SettingsPage.AppLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App 主题.
        /// </summary>
        public static string SettingsPage_AppTheme {
            get {
                return ResourceManager.GetString("SettingsPage.AppTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 代码仓库.
        /// </summary>
        public static string SettingsPage_CodeRepository {
            get {
                return ResourceManager.GetString("SettingsPage.CodeRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通用设置.
        /// </summary>
        public static string SettingsPage_CommonSettings {
            get {
                return ResourceManager.GetString("SettingsPage.CommonSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游戏本地化语言.
        /// </summary>
        public static string SettingsPage_GameLocalizationLanguage {
            get {
                return ResourceManager.GetString("SettingsPage.GameLocalizationLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游戏根目录.
        /// </summary>
        public static string SettingsPage_GameRootPath {
            get {
                return ResourceManager.GetString("SettingsPage.GameRootPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod 根目录.
        /// </summary>
        public static string SettingsPage_ModRootPath {
            get {
                return ResourceManager.GetString("SettingsPage.ModRootPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重启后生效.
        /// </summary>
        public static string SettingsPage_MustRestart {
            get {
                return ResourceManager.GetString("SettingsPage.MustRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在资源管理器中打开.
        /// </summary>
        public static string SettingsPage_OpenInExplorer {
            get {
                return ResourceManager.GetString("SettingsPage.OpenInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 其他.
        /// </summary>
        public static string SettingsPage_OtherSettings {
            get {
                return ResourceManager.GetString("SettingsPage.OtherSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重新选择.
        /// </summary>
        public static string SettingsPage_ReSelect {
            get {
                return ResourceManager.GetString("SettingsPage.ReSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 窗体背景.
        /// </summary>
        public static string SettingsPage_WindowBackdrop {
            get {
                return ResourceManager.GetString("SettingsPage.WindowBackdrop", resourceCulture);
            }
        }
    }
}
