//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moder.Language.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Moder.Language.Strings.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 亚克力.
        /// </summary>
        public static string Backdrop_Acrylic {
            get {
                return ResourceManager.GetString("Backdrop.Acrylic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 云母.
        /// </summary>
        public static string Backdrop_Mica {
            get {
                return ResourceManager.GetString("Backdrop.Mica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 云母 Alt.
        /// </summary>
        public static string Backdrop_MicaAlt {
            get {
                return ResourceManager.GetString("Backdrop.MicaAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无背景.
        /// </summary>
        public static string Backdrop_None {
            get {
                return ResourceManager.GetString("Backdrop.None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 攻击.
        /// </summary>
        public static string Character_Attack {
            get {
                return ResourceManager.GetString("Character.Attack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 协调.
        /// </summary>
        public static string Character_Coordination {
            get {
                return ResourceManager.GetString("Character.Coordination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 防御.
        /// </summary>
        public static string Character_Defense {
            get {
                return ResourceManager.GetString("Character.Defense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 等级.
        /// </summary>
        public static string Character_Level {
            get {
                return ResourceManager.GetString("Character.Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 后勤.
        /// </summary>
        public static string Character_Logistics {
            get {
                return ResourceManager.GetString("Character.Logistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 机动.
        /// </summary>
        public static string Character_Maneuvering {
            get {
                return ResourceManager.GetString("Character.Maneuvering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 计划.
        /// </summary>
        public static string Character_Planning {
            get {
                return ResourceManager.GetString("Character.Planning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图像(需在interface/*.gfx中定义).
        /// </summary>
        public static string CharacterEditor_Image {
            get {
                return ResourceManager.GetString("CharacterEditor.Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管理特质.
        /// </summary>
        public static string CharacterEditor_TraitManager {
            get {
                return ResourceManager.GetString("CharacterEditor.TraitManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 默认.
        /// </summary>
        public static string Common_Default {
            get {
                return ResourceManager.GetString("Common.Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        public static string Common_Delete {
            get {
                return ResourceManager.GetString("Common.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本地化名称.
        /// </summary>
        public static string Common_LocalizedName {
            get {
                return ResourceManager.GetString("Common.LocalizedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名称.
        /// </summary>
        public static string Common_Name {
            get {
                return ResourceManager.GetString("Common.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重命名.
        /// </summary>
        public static string Common_Rename {
            get {
                return ResourceManager.GetString("Common.Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        public static string Common_Save {
            get {
                return ResourceManager.GetString("Common.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 跟随系统设置.
        /// </summary>
        public static string Common_UseSystemSetting {
            get {
                return ResourceManager.GetString("Common.UseSystemSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 写入到文件.
        /// </summary>
        public static string Common_WriteToFile {
            get {
                return ResourceManager.GetString("Common.WriteToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 人物编辑器.
        /// </summary>
        public static string Menu_CharacterEditor {
            get {
                return ResourceManager.GetString("Menu.CharacterEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        public static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暂不支持此类型文件.
        /// </summary>
        public static string NotSupportFileTipInfo {
            get {
                return ResourceManager.GetString("NotSupportFileTipInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App 语言.
        /// </summary>
        public static string SettingsPage_AppLanguage {
            get {
                return ResourceManager.GetString("SettingsPage.AppLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App 主题.
        /// </summary>
        public static string SettingsPage_AppTheme {
            get {
                return ResourceManager.GetString("SettingsPage.AppTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 代码仓库.
        /// </summary>
        public static string SettingsPage_CodeRepository {
            get {
                return ResourceManager.GetString("SettingsPage.CodeRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通用设置.
        /// </summary>
        public static string SettingsPage_CommonSettings {
            get {
                return ResourceManager.GetString("SettingsPage.CommonSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游戏本地化语言.
        /// </summary>
        public static string SettingsPage_GameLocalizationLanguage {
            get {
                return ResourceManager.GetString("SettingsPage.GameLocalizationLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游戏根目录.
        /// </summary>
        public static string SettingsPage_GameRootPath {
            get {
                return ResourceManager.GetString("SettingsPage.GameRootPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod 根目录.
        /// </summary>
        public static string SettingsPage_ModRootPath {
            get {
                return ResourceManager.GetString("SettingsPage.ModRootPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重启后生效.
        /// </summary>
        public static string SettingsPage_MustRestart {
            get {
                return ResourceManager.GetString("SettingsPage.MustRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在资源管理器中打开.
        /// </summary>
        public static string SettingsPage_OpenInExplorer {
            get {
                return ResourceManager.GetString("SettingsPage.OpenInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 其他.
        /// </summary>
        public static string SettingsPage_OtherSettings {
            get {
                return ResourceManager.GetString("SettingsPage.OtherSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重新选择.
        /// </summary>
        public static string SettingsPage_ReSelect {
            get {
                return ResourceManager.GetString("SettingsPage.ReSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 窗体背景.
        /// </summary>
        public static string SettingsPage_WindowBackdrop {
            get {
                return ResourceManager.GetString("SettingsPage.WindowBackdrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 黑暗.
        /// </summary>
        public static string ThemeMode_Dark {
            get {
                return ResourceManager.GetString("ThemeMode.Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 明亮.
        /// </summary>
        public static string ThemeMode_Light {
            get {
                return ResourceManager.GetString("ThemeMode.Light", resourceCulture);
            }
        }
    }
}
